### ISSUE TITLE
Using Get-PagerDutyService

### ISSUE THREAD

**Issue by hales8181** [robcerda60/PagerDuty-PoSh-API-Client#1]
I'm trying to use Get-PagerDutyService -query  to filter by e-mail address as the service key - but I'm getting 
Cannot index into a null array.

Several of my services are using the same e-mail address as the service key...Is this the issue and is there a way of overcoming this?

**Comment by squid808** [comment]
Hi,

The 'Cannot index into a null array' issue has been fixed and pushed as of [the most recent commit](https://github.com/robcerda60/PagerDuty-PoSh-API-Client/commit/07246f3b6277edf9282cb44bb504c6f8a08d9797), sorry about that!

Regarding the query, you have to use either something that would be found in the service key or the service name as per their [API instructions](https://developer.pagerduty.com/documentation/rest/services/list):

> query: Filters the result, showing only the services whose name or service_key matches the query.

Give it a try with the newest version, and let me know if you still have issues.

**Comment by hales8181** [comment]
Ah - that works! Thanks

**Comment by squid808** [comment]
Glad to hear it. Stick with us, this is still an early project!
