### ISSUE TITLE
Issue with Get-PagerDutyMaintenaceWindows where the filter is null

### ISSUE THREAD

**Issue by hales8181** [robcerda60/PagerDuty-PoSh-API-Client#2]
When running Get-PagerDutyMaintenanceWindow with -filter, if the filter is empty (i.e using ongoing and there are currently no services in maintenance you get: 

Exception calling "ApiGet" with "3" argument(s): "Exception calling "ApiCallBase" with "5" argument(s): "Attempted to divide by zero.""

**Comment by squid808** [comment]
Try the most recent updates. As of the time of writing, with no services in maintenance, if I run the following:

`Get-PagerDutyMaintenanceWindow -Filter ongoing`

I just get a null result set. Can you confirm?

**Comment by squid808** [comment]
Hi Hales, I just wanted to check in and see if the updates made any difference. Thanks!

**Comment by hales8181** [comment]
Sorry, I missed this! I'll check now, thanks :)

**Comment by hales8181** [comment]
Perfect, all working - thanks!

**Comment by squid808** [comment]
Awesome, thanks so much for checking! Also, if you get a chance please check out [Issue #3](https://github.com/robcerda60/PagerDuty-PoSh-API-Client/issues/3) - I am using a trial account so I can't fully test everything out. If you have a chance and you're able to test some of those things out, I'd really appreciate it!

**Comment by hales8181** [comment]
I'm working my way through some of the stuff anyway - I promise once I've worked my own way through I'll hit your list :)
